
/* Agregar registros de MONEDA */
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(1, 'AED', 'Dírham de los Emiratos Árabes Unidos');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(2, 'AFN', 'Afgani');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(3, 'ALL', 'Lek');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(4, 'AMD', 'Dram armenio');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(5, 'ANG', 'Florín antillano neerlandés');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(6, 'AOA', 'Kwanza');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(7, 'ARS', 'Peso argentino');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(8, 'AUD', 'Dólar australiano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(9, 'AWG', 'Florín arubeño');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(10, 'AZN', 'Manat azerbaiyano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(11, 'BAM', 'Marco convertible');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(12, 'BBD', 'Dólar de Barbados');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(13, 'BDT', 'Taka');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(14, 'BGN', 'Lev búlgaro');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(15, 'BHD', 'Dinar bareiní');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(16, 'BIF', 'Franco de Burundi');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(17, 'BMD', 'Dólar bermudeño');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(18, 'BND', 'Dólar de Brunéi');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(19, 'BOB', 'Boliviano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(20, 'BOV', 'MVDOL');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(21, 'BRL', 'Real brasileño');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(22, 'BSD', 'Dólar bahameño');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(23, 'BTN', 'Ngultrum');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(24, 'BWP', 'Pula');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(25, 'BYR', 'Rublo bielorruso');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(26, 'BZD', 'Dólar beliceño');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(27, 'CAD', 'Dólar canadiense');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(28, 'CDF', 'Franco congoleño');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(29, 'CHE', 'Euro WIR');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(30, 'CHF', 'Franco suizo');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(31, 'CHW', 'Franco WIR');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(32, 'CLF', 'Unidad de fomento');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(33, 'CLP', 'Peso chileno');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(34, 'CNY', 'Yuan chino');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(35, 'COP', 'Peso colombiano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(36, 'COU', 'Unidad de valor real');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(37, 'CRC', 'Colón costarricense');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(38, 'CUC', 'Peso convertible');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(39, 'CUP', 'Peso cubano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(40, 'CVE', 'Escudo caboverdiano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(41, 'CZK', 'Corona checa');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(42, 'DJF', 'Franco yibutiano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(43, 'DKK', 'Corona danesa');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(44, 'DOP', 'Peso dominicano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(45, 'DZD', 'Dinar argelino');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(46, 'EGP', 'Libra egipcia');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(47, 'ERN', 'Nakfa');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(48, 'ETB', 'Birr etíope');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(49, 'EUR', 'Euro');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(50, 'FJD', 'Dólar fiyiano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(51, 'FKP', 'Libra malvinense');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(52, 'GBP', 'Libra esterlina');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(53, 'GEL', 'Lari');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(54, 'GHS', 'Cedi ghanés');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(55, 'GIP', 'Libra de Gibraltar');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(56, 'GMD', 'Dalasi');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(57, 'GNF', 'Franco guineano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(58, 'GTQ', 'Quetzal');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(59, 'GYD', 'Dólar guyanés');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(60, 'HKD', 'Dólar de Hong Kong');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(61, 'HNL', 'Lempira');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(62, 'HRK', 'Kuna');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(63, 'HTG', 'Gourde');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(64, 'HUF', 'Forinto');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(65, 'IDR', 'Rupia indonesia');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(66, 'ILS', 'Nuevo shéquel israelí');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(67, 'INR', 'Rupia india');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(68, 'IQD', 'Dinar iraquí');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(69, 'IRR', 'Rial iraní');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(70, 'ISK', 'Corona islandesa');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(71, 'JMD', 'Dólar jamaiquino');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(72, 'JOD', 'Dinar jordano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(73, 'JPY', 'Yen');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(74, 'KES', 'Chelín keniano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(75, 'KGS', 'Som');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(76, 'KHR', 'Riel');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(77, 'KMF', 'Franco comorense');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(78, 'KPW', 'Won norcoreano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(79, 'KRW', 'Won');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(80, 'KWD', 'Dinar kuwaití');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(81, 'KYD', 'Dólar de las Islas Caimán');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(82, 'KZT', 'Tenge');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(83, 'LAK', 'Kip');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(84, 'LBP', 'Libra libanesa');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(85, 'LKR', 'Rupia de Sri Lanka');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(86, 'LRD', 'Dólar liberiano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(87, 'LSL', 'Loti');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(88, 'LYD', 'Dinar libio');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(89, 'MAD', 'Dírham marroquí');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(90, 'MDL', 'Leu moldavo');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(91, 'MGA', 'Ariary malgache');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(92, 'MKD', 'Denar');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(93, 'MMK', 'Kyat');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(94, 'MNT', 'Tugrik');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(95, 'MOP', 'Pataca');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(96, 'MRO', 'Uguiya');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(97, 'MUR', 'Rupia de Mauricio');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(98, 'MVR', 'Rufiyaa');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(99, 'MWK', 'Kwacha');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(100, 'MXN', 'Peso mexicano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(101, 'MXV', 'Unidad de Inversión (UDI); mexicana');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(102, 'MYR', 'Ringgit malayo');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(103, 'MZN', 'Metical mozambiqueño');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(104, 'NAD', 'Dólar namibio');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(105, 'NGN', 'Naira');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(106, 'NIO', 'Córdoba');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(107, 'NOK', 'Corona noruega');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(108, 'NPR', 'Rupia nepalí');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(109, 'NZD', 'Dólar neozelandés');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(110, 'OMR', 'Rial omaní');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(111, 'PAB', 'Balboa');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(112, 'PEN', 'Sol');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(113, 'PGK', 'Kina');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(114, 'PHP', 'Peso filipino');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(115, 'PKR', 'Rupia pakistaní');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(116, 'PLN', 'Zloty');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(117, 'PYG', 'Guaraní');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(118, 'QAR', 'Riyal qatarí');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(119, 'RON', 'Leu rumano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(120, 'RSD', 'Dinar serbio');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(121, 'RUB', 'Rublo ruso');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(122, 'RWF', 'Franco ruandés');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(123, 'SAR', 'Riyal saudí');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(124, 'SBD', 'Dólar de las Islas Salomón');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(125, 'SCR', 'Rupia seychelense');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(126, 'SDG', 'Dinar sudanés');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(127, 'SEK', 'Corona sueca');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(128, 'SGD', 'Dólar de Singapur');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(129, 'SHP', 'Libra de Santa Elena');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(130, 'SLL', 'Leone');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(131, 'SOS', 'Chelín somalí');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(132, 'SRD', 'Dólar surinamés');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(133, 'SSP', 'Libra sursudanesa');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(134, 'STD', 'Dobra');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(135, 'SVC', 'Colon Salvadoreño');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(136, 'SYP', 'Libra siria');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(137, 'SZL', 'Lilangeni');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(138, 'THB', 'Baht');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(139, 'TJS', 'Somoni tayiko');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(140, 'TMT', 'Manat turcomano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(141, 'TND', 'Dinar tunecino');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(142, 'TOP', 'Pa´anga');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(143, 'TRY', 'Lira turca');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(144, 'TTD', 'Dólar de Trinidad y Tobago');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(145, 'TWD', 'Nuevo dólar taiwanés');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(146, 'TZS', 'Chelín tanzano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(147, 'UAH', 'Grivna');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(148, 'UGX', 'Chelín ugandés');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(149, 'USD', 'Dólar estadounidense');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(150, 'USN', 'Dólar estadounidense (Siguiente día);');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(151, 'UYI', 'Peso en Unidades Indexadas (Uruguay);');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(152, 'UYU', 'Peso uruguayo');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(153, 'UZS', 'Som uzbeko');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(154, 'VEF', 'Bolívar');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(155, 'VES7', 'Bolívar soberano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(156, 'VND', 'Dong vietnamita');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(157, 'VUV', 'Vatu');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(158, 'WST', 'Tala');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(159, 'XAF', 'Franco CFA de África Central');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(160, 'XAG', 'Plata (una onza troy);');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(161, 'XAU', 'Oro (una onza troy);');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(162, 'XBA', 'Unidad compuesta europea (EURCO); (Unidad del mercado de bonos);');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(163, 'XBB', 'Unidad Monetaria europea (E.M.U.-6); (Unidad del mercado de bonos);');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(164, 'XBC', 'Unidad europea de cuenta 9 (E.U.A.-9); (Unidad del mercado de bonos);');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(165, 'XBD', 'Unidad europea de cuenta 17 (E.U.A.-17); (Unidad del mercado de bonos);');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(166, 'XCD', 'Dólar del Caribe Oriental');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(167, 'XDR', 'Derechos especiales de giro');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(168, 'XOF', 'Franco CFA de África Occidental');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(169, 'XPD', 'Paladio (una onza troy);');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(170, 'XPF', 'Franco CFP');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(171, 'XPT', 'Platino (una onza troy);');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(172, 'XSU', 'SUCRE');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(173, 'XUA', 'Unidad de cuenta BAD');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(174, 'YER', 'Rial yemení');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(175, 'ZAR', 'Rand');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(176, 'ZMW', 'Kwacha zambiano');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(177, 'ZWL', 'Dólar zimbabuense');
